sudo: required

language: python

cache:
  - pip

services:
  - postgres

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - apt install nano

before_script:
  - psql -c 'create database travis;' -U postgres
  - psql -c "create user user_hg with password '12345';"
  - psql -c 'alter user user_hg with superuser;'
  # - psql -c 'create database test_bd_hg with owner user_hg;'
  - psql -c 'create database bd_hg with owner user_hg;'

script:
  - python manage.py syncdb --noinput &&\
  - python manage.py migrate userena &&\
  - python manage.py migrate easy_thumbnails &&\
  - python manage.py migrate django_extensions &&\
  - python manage.py migrate django_cron &&\
  - python manage.py migrate guardian
  # tests
  - coverage run manage.py test ; coverage report -m
  #- coverage run --source='.' manage.py test ; coverage report -m

after_success:
  - coveralls
  #- codeclimate-test-reporter --token $CODECLIMATE_REPO_TOKEN
