sudo: required

language: python

cache:
  - pip
  - apt

services:
  - postgres

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database travis;' -U postgres
  - psql -c "create user user_hg with password '12345';"
  - psql -c 'alter user user_hg with superuser;'
  - psql -c 'create database test_bd_hg with owner user_hg;'

script:
  # tests
  - coverage run --source='.' manage.py test ; coverage report -m

after_success:
  - codeclimate-test-reporter --token $CODECLIMATE_REPO_TOKEN

addons:
  code_climate:
    repo_token: "$CODECLIMATE_REPO_TOKEN"
