CREATE USER user_hg WITH PASSWORD '12345';
ALTER USER user_hg WITH SUPERUSER;
CREATE DATABASE bd_hg WITH OWNER user_hg;
CREATE DATABASE test_bd_hg WITH OWNER user_hg;
GRANT ALL PRIVILEGES ON DATABASE bd_hg TO user_hg;
